import Head from "next/head";
import styles from "../styles/Home.module.css";
import AllPagesView from "../components/pages/AllPagesView";

export default function Home({ pages }) {
  console.log("pages", pages);

  return (
    <div className={styles.container}>
      <Head>
        <title>PagesCMS</title>
        <meta name="description" content="Generated by PagesCMS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Pages CMS!</a>
        </h1>

        <p className={styles.description}>Get started by editing some pages.</p>

        <AllPagesView />

      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Powered by <span className={styles.logo}>Amir MC</span>
        </a>
      </footer>
    </div>
  );
}